apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth
spec:
  replicas: {{ .Values.replicas.auth }}
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: "{{ include "streamingapp.registry" . }}/{{ .Values.ecr.repositoryPrefix }}-auth:{{ .Values.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: PORT
              value: "3001"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: streamingapp-secrets
                  key: MONGO_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: streamingapp-secrets
                  key: JWT_SECRET
            - name: CLIENT_URLS
              valueFrom:
                configMapKeyRef:
                  name: streamingapp-config
                  key: CLIENT_URLS
---
apiVersion: v1
kind: Service
metadata:
  name: auth-svc
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - port: 3001
      targetPort: 3001