apiVersion: v1
kind: ConfigMap
metadata:
  name: streamingapp-config
data:
  AWS_REGION: {{ .Values.global.awsRegion | quote }}
  CLIENT_URLS: {{ .Values.global.clientUrls | quote }}
  AWS_STS_REGIONAL_ENDPOINTS: "regional"