apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: streamingapp-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /api/$2
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  rules:
    - host: streamingapp.local
      http:
        paths:
          - path: /api/auth(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: auth-svc
                port:
                  number: 3001
          - path: /api/streaming(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: streaming-svc
                port:
                  number: 3002
          - path: /api/admin(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: admin-svc
                port:
                  number: 3003
          - path: /api/chat(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: chat-svc
                port:
                  number: 3004
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-svc
                port:
                  number: 3000