apiVersion: v1
kind: Secret
metadata:
  name: streamingapp-secrets
type: Opaque
data:
  MONGO_URI: {{ default "mongodb://mongo-svc:27017/streamingapp" .Values.secrets.mongoUri | b64enc | quote }}
  JWT_SECRET: {{ default "supersecretjwtkeychangeinprod" .Values.secrets.jwtSecret | b64enc | quote }}